-- PostgreSQL seed data for UAE .NET jobs
-- Run this after creating the database and running migrations

-- Create sample .NET jobs for UAE
INSERT INTO "Jobs" ("Title", "Company", "Description", "Requirements", "Location", "Emirate", "SalaryMin", "SalaryMax", "Currency", "ExperienceLevel", "JobType", "Source", "ExternalUrl", "ExternalId", "Technologies", "Benefits", "IsActive", "PostedDate", "CreatedAt", "UpdatedAt")
VALUES 
-- Dubai Jobs
('Senior .NET Developer', 'Emirates NBD', 'Looking for an experienced .NET developer to join our digital banking team. You will work on mission-critical applications serving millions of customers across the UAE.', 'Minimum 5 years experience with .NET Core, C#, ASP.NET MVC, Entity Framework, SQL Server, and Azure cloud services. Experience with microservices architecture preferred.', 'Dubai International Financial Centre', 'Dubai', 25000, 35000, 'AED', 'Senior', 'Full-time', 'Manual', 'https://careers.emiratesnbd.com', 'ENBD001', '["ASP.NET Core", "C#", "Entity Framework", "SQL Server", "Azure", "Microservices"]', '["Health Insurance", "Annual Leave", "Performance Bonus", "Training Budget"]', true, NOW(), NOW(), NOW()),

('Full Stack .NET Developer', 'Careem', 'Join Careem as a Full Stack Developer working on our ride-hailing platform. You will be responsible for both frontend and backend development using modern .NET technologies.', '3+ years experience with .NET Core, React/Angular, REST APIs, and cloud platforms. Knowledge of mobile app integration is a plus.', 'Dubai Internet City', 'Dubai', 18000, 28000, 'AED', 'Mid-Level', 'Full-time', 'Manual', 'https://careers.careem.com', 'CAREEM001', '[".NET Core", "React", "Angular", "REST API", "Azure", "Docker"]', '["Flexible Hours", "Remote Work", "Stock Options", "Health Insurance"]', 1, GETDATE(), GETDATE(), GETDATE()),

('Lead .NET Architect', 'ADNOC', 'Lead architect position for designing and implementing enterprise-level .NET solutions for ADNOC digital transformation initiatives.', '8+ years experience in .NET development with 3+ years in architecture roles. Strong knowledge of Azure, microservices, and enterprise integration patterns.', 'Abu Dhabi Corniche', 'Abu Dhabi', 40000, 55000, 'AED', 'Lead', 'Full-time', 'Manual', 'https://careers.adnoc.ae', 'ADNOC001', '[".NET Framework", ".NET Core", "Azure", "Microservices", "Enterprise Architecture"]', '["Housing Allowance", "Transportation", "Health Insurance", "Annual Bonus"]', 1, GETDATE(), GETDATE(), GETDATE()),

('Junior .NET Developer', 'Majid Al Futtaim', 'Entry-level position for recent graduates or developers with 1-2 years experience. Work on e-commerce and retail solutions.', 'Bachelor''s degree in Computer Science and 1-2 years experience with C#, ASP.NET, and SQL Server. Fresh graduates with strong academic background welcome.', 'Dubai Mall, Downtown Dubai', 'Dubai', 10000, 16000, 'AED', 'Junior', 'Full-time', 'Manual', 'https://careers.majidalfuttaim.com', 'MAF001', '["C#", "ASP.NET", "SQL Server", "JavaScript", "HTML/CSS"]', '["Training Programs", "Career Development", "Health Insurance", "Mall Discounts"]', true, NOW(), NOW(), NOW()),

-- Abu Dhabi Jobs
('.NET Software Engineer', 'ADCB (Abu Dhabi Commercial Bank)', 'Software Engineer role focusing on digital banking solutions and customer-facing applications using latest .NET technologies.', '3-5 years experience with .NET Core, Web API, SQL Server, and experience in banking or financial services preferred.', 'ADCB Head Office, Abu Dhabi', 'Abu Dhabi', 20000, 30000, 'AED', 'Mid-Level', 'Full-time', 'Manual', 'https://careers.adcb.com', 'ADCB001', '[".NET Core", "Web API", "SQL Server", "JavaScript", "Banking Systems"]', '["Bank Benefits", "Health Insurance", "Annual Leave", "Training"]', true, NOW(), NOW(), NOW()),

('Senior Full Stack Developer', 'Etisalat', 'Senior developer role working on telecommunications and digital services platforms. Hybrid work arrangement available.', '5+ years experience with .NET, Angular/React, microservices, and cloud technologies. Telecom industry experience is a plus.', 'Etisalat Academy, Abu Dhabi', 'Abu Dhabi', 28000, 38000, 'AED', 'Senior', 'Full-time', 'Manual', 'https://careers.etisalat.ae', 'ETISALAT001', '[".NET Core", "Angular", "Microservices", "Azure", "DevOps"]', '["Hybrid Work", "Health Insurance", "Telecom Benefits", "Professional Development"]', true, NOW(), NOW(), NOW()),

-- Sharjah Jobs
('.NET Application Developer', 'Sharjah Investment Authority', 'Develop and maintain investment management applications and reporting systems using .NET technologies.', '2-4 years experience with .NET Framework, ASP.NET MVC, Entity Framework, and SQL Server. Experience with financial systems preferred.', 'Sharjah Government Complex', 'Sharjah', 15000, 22000, 'AED', 'Mid-Level', 'Full-time', 'Manual', 'https://sia.gov.ae/careers', 'SIA001', '[".NET Framework", "ASP.NET MVC", "Entity Framework", "SQL Server", "Financial Systems"]', '["Government Benefits", "Job Security", "Health Insurance", "Pension Plan"]', true, NOW(), NOW(), NOW()),

-- Remote/Multiple Locations
('Remote .NET Developer', 'Noon.com', 'Remote position for .NET developer to work on e-commerce platform serving MENA region. Flexible working hours across time zones.', '3+ years experience with .NET Core, microservices, Docker, and Kubernetes. E-commerce or marketplace experience preferred.', 'Remote (UAE based)', 'Dubai', 22000, 32000, 'AED', 'Mid-Level', 'Remote', 'Manual', 'https://careers.noon.com', 'NOON001', '[".NET Core", "Microservices", "Docker", "Kubernetes", "E-commerce"]', '["Remote Work", "Flexible Hours", "Health Insurance", "Stock Options"]', true, NOW(), NOW(), NOW()),

('C# Backend Developer', 'Talabat', 'Backend developer role focusing on food delivery platform scalability and performance optimization.', '2-5 years experience with C#, .NET Core, Redis, Message Queues, and high-traffic applications. Experience with food tech or delivery platforms is a plus.', 'Multiple UAE Locations', 'Dubai', 19000, 29000, 'AED', 'Mid-Level', 'Full-time', 'Manual', 'https://careers.talabat.com', 'TALABAT001', '["C#", ".NET Core", "Redis", "Message Queues", "High Traffic Applications"]', '["Food Allowance", "Health Insurance", "Stock Options", "Flexible Hours"]', true, NOW(), NOW(), NOW()),

('DevOps Engineer (.NET Focus)', 'Dubai Health Authority', 'DevOps engineer with strong .NET background to manage healthcare applications deployment and infrastructure.', '4+ years experience with .NET applications, Azure DevOps, Docker, Kubernetes, and CI/CD pipelines. Healthcare industry experience preferred.', 'Dubai Healthcare City', 'Dubai', 25000, 35000, 'AED', 'Senior', 'Full-time', 'Manual', 'https://dha.gov.ae/careers', 'DHA001', '["DevOps", ".NET", "Azure DevOps", "Docker", "Kubernetes", "Healthcare Systems"]', '["Government Benefits", "Health Insurance", "Professional Development", "Job Security"]', true, NOW(), NOW(), NOW());

GO